feat: move amplitude api key to runtime.exs (#1)
Signed-off-by: yqrashawn <namy.19@gmail.com>

diff --git a/.github/workflows/publish-docker-image-release.yml b/.github/workflows/publish-docker-image-release.yml
--- a/.github/workflows/publish-docker-image-release.yml
+++ b/.github/workflows/publish-docker-image-release.yml
@@ -10,8 +10,8 @@ on:
     types: [published]
 
 env:
-  OTP_VERSION: '25.2.1'
-  ELIXIR_VERSION: '1.14.3'
+  OTP_VERSION: "25.2.1"
+  ELIXIR_VERSION: "1.14.3"
 
 jobs:
   push_to_registry:
@@ -32,14 +32,14 @@ jobs:
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
         uses: docker/metadata-action@v4
         with:
-          images: blockscout/blockscout
+          images: ${{ secrets.DOCKERHUB_USERNAME }}/blockscout
 
       - name: Build & Push Docker image
         uses: docker/build-push-action@v3
@@ -47,9 +47,9 @@ jobs:
           context: .
           file: ./docker/Dockerfile
           push: true
-          cache-from: type=registry,ref=blockscout/blockscout:buildcache
-          cache-to: type=registry,ref=blockscout/blockscout:buildcache,mode=max
-          tags: blockscout/blockscout:latest, blockscout/blockscout:${{ env.RELEASE_VERSION }}
+          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/blockscout:buildcache
+          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/blockscout:buildcache,mode=max
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blockscout:latest, ${{ secrets.DOCKERHUB_USERNAME }}/blockscout:${{ env.RELEASE_VERSION }}
           platforms: |
             linux/arm64
             linux/amd64
@@ -64,57 +64,57 @@ jobs:
             MIXPANEL_URL=
             MIXPANEL_TOKEN=
             AMPLITUDE_URL=
-            AMPLITUDE_API_KEY=
+            AMPLITUDE_API_KEY= ${{ secrets.AMPLITUDE_API_KEY }}
             CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
             BLOCKSCOUT_VERSION=v${{ env.RELEASE_VERSION }}-beta
             RELEASE_VERSION=${{ env.RELEASE_VERSION }}
 
-  merge-master-after-release:
-    name: Merge 'master' to specific branch after release
-    runs-on: ubuntu-latest
-    env:
-      BRANCHES: |
-        production-core-stg
-        production-sokol-stg
-        vb-eth-tests
-        production-eth-goerli-stg
-        production-withdrawals-stg
-        production-harmony-mainnet-shard-0-stg
-        production-lukso-stg
-        production-optimism-goerli-stg
-        production-optimism-mainnet-stg
-        production-optimism-bedrock-goerli-stg
-        production-optimism-opcraft-stg
-        production-xdai-stg
-        production-gc-chiado-stg
-        production-polygon-supernets-stg
-        production-base-goerli-stg
-        production-rsk-stg
-        production-neon-stg
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set Git config
-      run: |
-          git config --local user.email "actions@github.com"
-          git config --local user.name "Github Actions"
-    - name: Merge master back after release
-      run: |
-          git fetch --unshallow
-          touch errors.txt
-          for branch in $BRANCHES;
-          do
-            git reset --merge
-            git checkout master
-            git fetch origin
-            echo $branch
-            git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
-            echo "Merge 'master' to $branch"
-            git checkout $branch
-            git pull || { echo $branch >> errors.txt; continue; }
-            git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
-            git push || { echo $branch >> errors.txt; continue; }
-            git checkout master;
-          done
-          [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
-          cat errors.txt
-          [ ! -s errors.txt ]
+  # merge-master-after-release:
+  #   name: Merge 'master' to specific branch after release
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     BRANCHES: |
+  #       production-core-stg
+  #       production-sokol-stg
+  #       vb-eth-tests
+  #       production-eth-goerli-stg
+  #       production-withdrawals-stg
+  #       production-harmony-mainnet-shard-0-stg
+  #       production-lukso-stg
+  #       production-optimism-goerli-stg
+  #       production-optimism-mainnet-stg
+  #       production-optimism-bedrock-goerli-stg
+  #       production-optimism-opcraft-stg
+  #       production-xdai-stg
+  #       production-gc-chiado-stg
+  #       production-polygon-supernets-stg
+  #       production-base-goerli-stg
+  #       production-rsk-stg
+  #       production-neon-stg
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Set Git config
+  #       run: |
+  #         git config --local user.email "actions@github.com"
+  #         git config --local user.name "Github Actions"
+  #     - name: Merge master back after release
+  #       run: |
+  #         git fetch --unshallow
+  #         touch errors.txt
+  #         for branch in $BRANCHES;
+  #         do
+  #           git reset --merge
+  #           git checkout master
+  #           git fetch origin
+  #           echo $branch
+  #           git ls-remote --exit-code --heads origin $branch || { echo $branch >> errors.txt; continue; }
+  #           echo "Merge 'master' to $branch"
+  #           git checkout $branch
+  #           git pull || { echo $branch >> errors.txt; continue; }
+  #           git merge --no-ff master -m "Auto-merge master back to $branch" || { echo $branch >> errors.txt; continue; }
+  #           git push || { echo $branch >> errors.txt; continue; }
+  #           git checkout master;
+  #         done
+  #         [ -s errors.txt ] && echo "There are problems with merging 'master' to branches:" || echo "Errors file is empty"
+  #         cat errors.txt
+  #         [ ! -s errors.txt ]
